"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.metadata = void 0;
exports.default = RootLayout;
var google_1 = require("next/font/google");
require("./globals.css");
var GlobalContext_1 = require("@/context/GlobalContext");
var Alert_1 = require("@/components/Alert");
var NavigationBar_1 = require("@/components/NavigationBar");
var getFolders_1 = require("@/utils/common/getFolders");
var urbanist = (0, google_1.Urbanist)({ subsets: ['latin'] });
exports.metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};
function RootLayout(_a) {
    var children = _a.children;
    var folders = (0, getFolders_1.getFolders)();
    return (React.createElement("html", { lang: "en" },
        React.createElement("body", { className: "antialiased" },
            React.createElement(GlobalContext_1.GlobalProvider, null,
                React.createElement(Alert_1.GlobalAlert, null),
                React.createElement("div", { className: "".concat(urbanist.className, " flex flex-col h-full min-h-screen") },
                    React.createElement("div", { className: "fixed top-0 left-0 right-0 z-10" },
                        React.createElement(NavigationBar_1.NavBar, null)),
                    React.createElement("div", { className: "flex flex-grow pt-[64px]" },
                        React.createElement("div", { className: "fixed top-[64px] left-0 h-[calc(100vh-64px)] w-72 z-10" },
                            React.createElement(NavigationBar_1.SideBar, { folders: folders })),
                        React.createElement("main", { className: "flex-grow ml-72 p-6 overflow-y-auto" }, children)))))));
}
