import type { Metadata } from "next";
import { Urbanist } from 'next/font/google'
import "./globals.css";
import { GlobalProvider } from "@/context/GlobalContext";
import { GlobalAlert } from "@/components/Alert";
import { NavBar, SideBar } from "@/components/NavigationBar";
import { getFolders } from "@/utils/common/getFolders";

const urbanist = Urbanist({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const folders = getFolders();

  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <GlobalProvider>
          <GlobalAlert />
          <div className={`${urbanist.className} flex flex-col h-full min-h-screen`}>
            <div className="fixed top-0 left-0 right-0 z-10">
              <NavBar />
            </div>
            <div className="flex flex-grow pt-[64px]">
              <div className="fixed top-[64px] left-0 h-[calc(100vh-64px)] w-72 z-10">
                <SideBar folders={folders} />
              </div>
              <main className={`flex-grow ml-72 p-6 overflow-y-auto`}>
                {children}
              </main>
            </div>
          </div>
        </GlobalProvider>
      </body>
    </html>
  );
}
